version: '3'

services:

  api-service:
    image: 'node'
    container_name: 'duna_delivery_api_node'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${SERVER_PORT}:3000"
      - 9229:9229
    environment:
      SERVER_HOST: "${SERVER_HOST}"
      SERVER_PORT: "${SERVER_PORT}"
      MONGO_URL: "mongodb://${MONGO_USER}:${MONGO_PASS}@duna_delivery_api_mongo:${MONGO_PORT}/$MONGO_DBNAME"
    depends_on:
      - db-service
    command: /bin/bash -c "npm run dev"

  db-service:
    image: mongo
    restart: always
    container_name: 'duna_delivery_api_mongo'
    volumes:
      - mongo-volume:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
      MONGO_INITDB_DATABASE: "${MONGO_DBNAME}"

volumes:
  mongo-volume: {}
