### ping ======================================================================

GET http://localhost:3000/ping
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTIyMDQ2NCwiZXhwIjoxNTk1MjI0MDY0LCJhdWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJpc3MiOiJ4ZWxleC5jbyJ9.OBwrM-Cq6xq6581cdqroAFOksFjkq3WryQX1FgZFxdg

### auth ======================================================================

### 1....
### 2.
### REGISTER:
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": { "first": "Norman", "last": "Carcamo" },
  "email": "normancarcamo@gmail.com",
  "password": "norman123",
  "phone": "32359444",
  "photo": "https://s3.amazonaws.com/uifaces/faces/twitter/yehudab/128.jpg",
  "address": {
    "latitude": 14.078505,
    "streetAddress": "Barrio La Granja",
    "longitude": -87.209027
  }
}

### 3.
### LOGIN:
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "normancarcamo@gmail.com",
  "password": "norman123"
}

### LOGOUT:
DELETE http://localhost:3000/auth/logout
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTIyMDQ2NCwiZXhwIjoxNTk1MjI0MDY0LCJhdWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJpc3MiOiJ4ZWxleC5jbyJ9.OBwrM-Cq6xq6581cdqroAFOksFjkq3WryQX1FgZFxdg

### REFRESH TOKEN:
POST http://localhost:3000/auth/refresh-token
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTIyMDQ2NCwiZXhwIjoxNTk1MjI0MDY0LCJhdWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJpc3MiOiJ4ZWxleC5jbyJ9.OBwrM-Cq6xq6581cdqroAFOksFjkq3WryQX1FgZFxdg

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTUyMjA0NjQsImV4cCI6MTYyNjc3ODA2NCwiYXVkIjoiNWYxM2JjNDZmZTIzYTkwMmJlMTQ0MjYzIiwiaXNzIjoieGVsZXguY28ifQ.VNJyavJAquizLpEgZFDB-XGJyDwM-trpzUVf87SRTZI"
}

### orders ====================================================================

### Get all orders:
GET http://localhost:3000/orders
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTIyMDQ2NCwiZXhwIjoxNTk1MjI0MDY0LCJhdWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJpc3MiOiJ4ZWxleC5jbyJ9.OBwrM-Cq6xq6581cdqroAFOksFjkq3WryQX1FgZFxdg

### Create order:
POST http://localhost:3000/orders
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTIyMDQ2NCwiZXhwIjoxNTk1MjI0MDY0LCJhdWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJpc3MiOiJ4ZWxleC5jbyJ9.OBwrM-Cq6xq6581cdqroAFOksFjkq3WryQX1FgZFxdg

### Get pending order:
GET http://localhost:3000/orders/pending
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTIyMDQ2NCwiZXhwIjoxNTk1MjI0MDY0LCJhdWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJpc3MiOiJ4ZWxleC5jbyJ9.OBwrM-Cq6xq6581cdqroAFOksFjkq3WryQX1FgZFxdg

### Update order status: [canceled | delivering | delivered | pending | pickedUp | pickingUp]
PATCH http://localhost:3000/orders/5f14e566a33022064d34752a?status=canceled
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTIyMDQ2NCwiZXhwIjoxNTk1MjI0MDY0LCJhdWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJpc3MiOiJ4ZWxleC5jbyJ9.OBwrM-Cq6xq6581cdqroAFOksFjkq3WryQX1FgZFxdg

### seed ======================================================================

### 2....
### 1.
POST http://localhost:3000/seed
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTIyMDQ2NCwiZXhwIjoxNTk1MjI0MDY0LCJhdWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJpc3MiOiJ4ZWxleC5jbyJ9.OBwrM-Cq6xq6581cdqroAFOksFjkq3WryQX1FgZFxdg

{
  //"files": true,
  //"merge": true
}

### 3....
### 4.
### Seed only the current user:
POST http://localhost:3000/seed/user
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTIyMDQ2NCwiZXhwIjoxNTk1MjI0MDY0LCJhdWQiOiI1ZjEzYmM0NmZlMjNhOTAyYmUxNDQyNjMiLCJpc3MiOiJ4ZWxleC5jbyJ9.OBwrM-Cq6xq6581cdqroAFOksFjkq3WryQX1FgZFxdg

{
  "max": 60,
  "status": [
    "canceled",
    "delivered"
  ]
}
