### ping ======================================================================

GET http://localhost:3000/ping

### auth ======================================================================

### REGISTER:
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": { "first": "Norman", "last": "Carcamo" },
  "email": "normancarcamo@gmail.com",
  "password": "norman123",
  "phone": "32359444",
  "photo": "https://s3.amazonaws.com/uifaces/faces/twitter/yehudab/128.jpg",
  "address": {
    "latitude": 14.078505,
    "streetAddress": "Barrio La Granja",
    "longitude": -87.209027
  }
}

### LOGIN:
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "normancarcamo@gmail.com",
  "password": "norman123"
}

### LOGOUT:
DELETE http://localhost:3000/auth/logout
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTAyMzU2MCwiZXhwIjoxNTk1MDI3MTYwLCJhdWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJpc3MiOiJ4ZWxleC5jbyJ9.bvJrAhoX78iK0NygGreLB9Cs7brsCmB23BFFePpPEL4

### REFRESH TOKEN:
POST http://localhost:3000/auth/refresh-token
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTAyMzU2MCwiZXhwIjoxNTk1MDI3MTYwLCJhdWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJpc3MiOiJ4ZWxleC5jbyJ9.bvJrAhoX78iK0NygGreLB9Cs7brsCmB23BFFePpPEL4

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTUwMjM1NjAsImV4cCI6MTYyNjU4MTE2MCwiYXVkIjoiNWYxMjEyNjUyODQyNmMwNTFjZTQ2NjVkIiwiaXNzIjoieGVsZXguY28ifQ.kzDiLppv87CaeotBizOYAAvcNyekDXgOMX-5Yq-MsZM"
}

### orders ====================================================================

GET http://localhost:3000/orders
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTAyMzU2MCwiZXhwIjoxNTk1MDI3MTYwLCJhdWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJpc3MiOiJ4ZWxleC5jbyJ9.bvJrAhoX78iK0NygGreLB9Cs7brsCmB23BFFePpPEL4

### seed ======================================================================

### If you don't send the request as POST, you get error:
GET http://localhost:3000/seed
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTAyMzU2MCwiZXhwIjoxNTk1MDI3MTYwLCJhdWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJpc3MiOiJ4ZWxleC5jbyJ9.bvJrAhoX78iK0NygGreLB9Cs7brsCmB23BFFePpPEL4

### When the request doesn't include payload, you get ok:
POST http://localhost:3000/seed
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTAyMzU2MCwiZXhwIjoxNTk1MDI3MTYwLCJhdWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJpc3MiOiJ4ZWxleC5jbyJ9.bvJrAhoX78iK0NygGreLB9Cs7brsCmB23BFFePpPEL4

{
  //"files": true,
  //"merge": true
}

### Seed the current user:
POST http://localhost:3000/seed/user
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTAyMzU2MCwiZXhwIjoxNTk1MDI3MTYwLCJhdWQiOiI1ZjEyMTI2NTI4NDI2YzA1MWNlNDY2NWQiLCJpc3MiOiJ4ZWxleC5jbyJ9.bvJrAhoX78iK0NygGreLB9Cs7brsCmB23BFFePpPEL4
