### ping ======================================================================

GET http://localhost:3000/ping
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTA0NTI0MSwiZXhwIjoxNTk1MDQ4ODQxLCJhdWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJpc3MiOiJ4ZWxleC5jbyJ9.FyjyX2AXkmYBbI-ouAQErW3Ib-0F4LXspBLmrECRn-E

### auth ======================================================================

### REGISTER:
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": { "first": "Norman", "last": "Carcamo" },
  "email": "normancarcamo@gmail.com",
  "password": "norman123",
  "phone": "32359444",
  "photo": "https://s3.amazonaws.com/uifaces/faces/twitter/yehudab/128.jpg",
  "address": {
    "latitude": 14.078505,
    "streetAddress": "Barrio La Granja",
    "longitude": -87.209027
  }
}

### LOGIN:
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "normancarcamo@gmail.com",
  "password": "norman123"
}

### LOGOUT:
DELETE http://localhost:3000/auth/logout
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTA0NTI0MSwiZXhwIjoxNTk1MDQ4ODQxLCJhdWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJpc3MiOiJ4ZWxleC5jbyJ9.FyjyX2AXkmYBbI-ouAQErW3Ib-0F4LXspBLmrECRn-E

### REFRESH TOKEN:
POST http://localhost:3000/auth/refresh-token
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTA0NTI0MSwiZXhwIjoxNTk1MDQ4ODQxLCJhdWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJpc3MiOiJ4ZWxleC5jbyJ9.FyjyX2AXkmYBbI-ouAQErW3Ib-0F4LXspBLmrECRn-E

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTUwNDUyNDEsImV4cCI6MTYyNjYwMjg0MSwiYXVkIjoiNWYxMjc1Nzk2MDNhYTMwOTEzOTY2NzE5IiwiaXNzIjoieGVsZXguY28ifQ.amax43RZRPef_pSoeI2v72gYNqMuNLim8f38KPFk4P0"
}

### orders ====================================================================

### Get all orders from the current user logged with pagination.
GET http://localhost:3000/orders
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTA0NTI0MSwiZXhwIjoxNTk1MDQ4ODQxLCJhdWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJpc3MiOiJ4ZWxleC5jbyJ9.FyjyX2AXkmYBbI-ouAQErW3Ib-0F4LXspBLmrECRn-E

### Get stats, counts, totals:
GET http://localhost:3000/orders/stats
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTA0NTI0MSwiZXhwIjoxNTk1MDQ4ODQxLCJhdWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJpc3MiOiJ4ZWxleC5jbyJ9.FyjyX2AXkmYBbI-ouAQErW3Ib-0F4LXspBLmrECRn-E

### seed ======================================================================

### seed all users
POST http://localhost:3000/seed
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTA0NTI0MSwiZXhwIjoxNTk1MDQ4ODQxLCJhdWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJpc3MiOiJ4ZWxleC5jbyJ9.FyjyX2AXkmYBbI-ouAQErW3Ib-0F4LXspBLmrECRn-E

{
  //"files": true,
  //"merge": true
}

### Seed only the current user:
POST http://localhost:3000/seed/user
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJuYW1lIjp7ImZpcnN0IjoiTm9ybWFuIiwibGFzdCI6IkNhcmNhbW8ifSwiZW1haWwiOiJub3JtYW5jYXJjYW1vQGdtYWlsLmNvbSIsImlhdCI6MTU5NTA0NTI0MSwiZXhwIjoxNTk1MDQ4ODQxLCJhdWQiOiI1ZjEyNzU3OTYwM2FhMzA5MTM5NjY3MTkiLCJpc3MiOiJ4ZWxleC5jbyJ9.FyjyX2AXkmYBbI-ouAQErW3Ib-0F4LXspBLmrECRn-E
